bin_PROGRAMS = dynappsrc_stream dynappsrc_decodebin3 dynappsrc_playbin3
dynappsrc_stream_SOURCES = dynappsrc-stream.c
dynappsrc_stream_CFLAGS = $(GST_PLUGINS_BASE_CFLAGS) $(GST_BASE_CFLAGS) $(GST_CFLAGS)
dynappsrc_stream_LDFLAGS = \
  $(GST_LIBS)

dynappsrc_decodebin3_SOURCES = dynappsrc-decodebin3.c
dynappsrc_decodebin3_CFLAGS = $(GST_PLUGINS_BASE_CFLAGS) $(GST_BASE_CFLAGS) $(GST_CFLAGS)
dynappsrc_decodebin3_LDFLAGS = \
  $(GST_LIBS)

dynappsrc_playbin3_SOURCES = dynappsrc-playbin3.c
dynappsrc_playbin3_CFLAGS = $(GST_PLUGINS_BASE_CFLAGS) $(GST_BASE_CFLAGS) $(GST_CFLAGS)
dynappsrc_playbin3_LDFLAGS = \
  $(GST_LIBS)
