subdir('avibin')
subdir('cencdrm')
subdir('cooltracer')
subdir('dashsink')
subdir('decproxy')
subdir('dolbystreamcombiner')
subdir('dvcombbin')
subdir('dvrdashdemux')
subdir('dvrdrm')
subdir('dvrisomp4')
subdir('dvrtsdemux')
subdir('dynappsrc')
subdir('fakedec')
subdir('httpextbin')
subdir('mpomux')
subdir('reformatter')
subdir('splitappsink')
#subdir('streamiddemux')
subdir('textbin')
subdir('tsinkbin')
