[buffering]
max-size-buffers=0
max-size-bytes=0
max-size-time=20000000000
low-percent=10
high-percent=99
ring-buffer-max-size=0

[rank]
mpegpsdemux=310
alsasink=0
pulsesink=0
decproxy=300
mediainfo=64
osssink=0
oss4sink=0
dvdlpcmdec=290
adpcmdec=256
cencdrmplayready=290
cencdrmmarlin=260

[sw_decoder]
avdec_mp3=0
avdec_aac=0
avdec_ac3=0
avdec_dca=0
avdec_alac=0
avdec_amrnb=0
avdec_amrwb=0
avdec_eac3=0
wavpackdec=0
avdec_wmapro=0
avdec_wmav1=0
avdec_wmav2=0
avdec_wmavoice=0
alawdec=0
mulawdec=0
avdec_flac=0
adpcmdec=256
faad=0
dvdlpcmdec=290
vorbisdec=0

[default_sink]
video=dvovideosink
audio=rtkalsasink

[debug]
GST_TRACERS=
PMLOG_DEBUG_KLASS=Decoder&Codec,Audio&Sink,Video&Sink
PMLOG_DEBUG_ELEMENT=streamsynchronizer,multiqueue,decproxy,decbridge
PMLOG_DEBUG_EVENT=stream-start,caps,flush-start,flush-stop,seek,stream-collection
DEBUG_MODE=disable
GST_DEBUG=5
GST_DEBUG_FILE=/tmp/gst.log
GST_DEBUG_FILE_MAX_COUNT=2
GST_DEBUG_FILE_OVERWRITE=disable
GST_DEBUG_DUMP_DOT_DIR=/tmp
GST_DEBUG_NO_COLOR=1
DOT_GRAPH_TIMEOUT=0
